/**
 * Init CLI command - Generate and save a Veil keypair
 */

import { Command } from 'commander';
import { createInterface } from 'readline';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { dirname } from 'path';
import { mkdirSync } from 'fs';
import { Keypair } from '../../keypair.js';

/**
 * Prompt user for yes/no confirmation
 */
async function confirm(question: string): Promise<boolean> {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(`${question} (y/n): `, (answer) => {
      rl.close();
      resolve(answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes');
    });
  });
}

/**
 * Get the default path to .env.veil file (current directory)
 */
function getDefaultEnvPath(): string {
  return '.env.veil';
}

/**
 * Check if VEIL_KEY exists in an env file
 */
function veilKeyExistsAt(envPath: string): boolean {
  if (!existsSync(envPath)) return false;
  
  const content = readFileSync(envPath, 'utf-8');
  return /^VEIL_KEY=/m.test(content);
}

/**
 * Update or add a key in .env content
 */
function updateEnvVar(content: string, key: string, value: string): string {
  const regex = new RegExp(`^${key}=.*`, 'm');
  if (regex.test(content)) {
    return content.replace(regex, `${key}=${value}`);
  } else {
    if (content && !content.endsWith('\n')) {
      content += '\n';
    }
    return content + `${key}=${value}\n`;
  }
}

/**
 * Save Veil keypair to a file
 */
function saveVeilKeypair(veilKey: string, depositKey: string, envPath: string): void {
  // Ensure directory exists
  const dir = dirname(envPath);
  if (dir && dir !== '.' && !existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  
  let content = '';
  
  if (existsSync(envPath)) {
    content = readFileSync(envPath, 'utf-8');
  } else {
    content = '# Veil Cash Configuration\n# Generated by: veil init\n\n';
  }
  
  content = updateEnvVar(content, 'VEIL_KEY', veilKey);
  content = updateEnvVar(content, 'DEPOSIT_KEY', depositKey);
  
  writeFileSync(envPath, content);
}

export function createInitCommand(): Command {
  const init = new Command('init')
    .description('Generate a new Veil keypair')
    .option('--force', 'Overwrite existing keypair without prompting')
    .option('--json', 'Output as JSON (no prompts, no file save)')
    .option('--out <path>', 'Save to custom path instead of .env.veil')
    .option('--no-save', 'Print keypair without saving to file')
    .action(async (options) => {
      const envPath = options.out || getDefaultEnvPath();
      
      // JSON mode: no prompts, no save, just output JSON
      if (options.json) {
        const kp = new Keypair();
        console.log(JSON.stringify({
          veilKey: kp.privkey,
          depositKey: kp.depositKey(),
        }, null, 2));
        process.exit(0);
        return;
      }

      // No-save mode: print but don't save
      if (!options.save) {
        const kp = new Keypair();
        console.log('\nGenerated new Veil keypair:\n');
        console.log('Veil Private Key:');
        console.log(`  ${kp.privkey}\n`);
        console.log('Deposit Key (register this on-chain):');
        console.log(`  ${kp.depositKey()}\n`);
        console.log('(Not saved - use --out <path> to save to a file)');
        process.exit(0);
        return;
      }

      // Check if VEIL_KEY already exists (unless --force)
      const keyExists = veilKeyExistsAt(envPath);
      
      if (keyExists && !options.force) {
        console.log(`\nWARNING: A Veil key already exists in ${envPath}`);
        const proceed = await confirm('Create a new key? This will overwrite the existing one');
        if (!proceed) {
          console.log('Aborted. Existing key preserved.');
          process.exit(0);
          return;
        }
      }
      
      const kp = new Keypair();
      
      console.log('\nGenerated new Veil keypair:\n');
      console.log('Veil Private Key:');
      console.log(`  ${kp.privkey}\n`);
      console.log('Deposit Key (register this on-chain):');
      console.log(`  ${kp.depositKey()}\n`);
      
      saveVeilKeypair(kp.privkey!, kp.depositKey(), envPath);
      console.log(`Saved to ${envPath}`);
      console.log('\nNext step: veil register');
      process.exit(0);
    });

  return init;
}
