/**
 * Init CLI command - Generate and save a Veil keypair
 */

import { Command } from 'commander';
import { createInterface } from 'readline';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { dirname } from 'path';
import { mkdirSync } from 'fs';
import { Keypair } from '../../keypair.js';

/**
 * Prompt user for yes/no confirmation
 */
async function confirm(question: string): Promise<boolean> {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(`${question} (y/n): `, (answer) => {
      rl.close();
      resolve(answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes');
    });
  });
}

/**
 * Get the default path to .env.veil file (current directory)
 */
function getDefaultEnvPath(): string {
  return '.env.veil';
}

/**
 * Check if VEIL_KEY exists in an env file
 */
function veilKeyExistsAt(envPath: string): boolean {
  if (!existsSync(envPath)) return false;
  
  const content = readFileSync(envPath, 'utf-8');
  return /^VEIL_KEY=/m.test(content);
}

/**
 * Update or add a key in .env content
 */
function updateEnvVar(content: string, key: string, value: string): string {
  const regex = new RegExp(`^${key}=.*`, 'm');
  if (regex.test(content)) {
    return content.replace(regex, `${key}=${value}`);
  } else {
    if (content && !content.endsWith('\n')) {
      content += '\n';
    }
    return content + `${key}=${value}\n`;
  }
}

/**
 * Save Veil keypair to a file
 */
function saveVeilKeypair(veilKey: string, depositKey: string, envPath: string): void {
  // Ensure directory exists
  const dir = dirname(envPath);
  if (dir && dir !== '.' && !existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  
  let content = '';
  
  if (existsSync(envPath)) {
    content = readFileSync(envPath, 'utf-8');
  } else {
    content = '# Veil Cash Configuration\n# Generated by: veil init\n\n';
  }
  
  content = updateEnvVar(content, 'VEIL_KEY', veilKey);
  content = updateEnvVar(content, 'DEPOSIT_KEY', depositKey);
  
  writeFileSync(envPath, content);
}

/**
 * Resolve wallet key from CLI flag or WALLET_KEY env var
 */
function resolveWalletKey(options: { walletKey?: string }): `0x${string}` {
  const raw = options.walletKey || process.env.WALLET_KEY;
  if (!raw) {
    throw new Error('Wallet key required for --sign-message. Use --wallet-key <key> or set WALLET_KEY env var.');
  }
  const key = raw.startsWith('0x') ? raw : `0x${raw}`;
  if (key.length !== 66) {
    throw new Error('Invalid wallet key format. Must be a 0x-prefixed 64-character hex string.');
  }
  return key as `0x${string}`;
}

export function createInitCommand(): Command {
  const init = new Command('init')
    .description('Generate a new Veil keypair')
    .option('--force', 'Overwrite existing keypair without prompting')
    .option('--json', 'Output as JSON (no prompts, no file save)')
    .option('--no-save', 'Print keypair without saving to file')
    .option('--sign-message', 'Derive keypair from wallet signature (same as frontend login)')
    .option('--wallet-key <key>', 'Ethereum wallet private key (or set WALLET_KEY env var)')
    .option('--signature <sig>', 'Derive keypair from a pre-computed EIP-191 personal_sign signature')
    .action(async (options) => {
      const envPath = getDefaultEnvPath();
      
      /**
       * Create keypair: derived from wallet, from signature, or random
       */
      async function createKp(): Promise<Keypair> {
        if (options.signMessage) {
          const walletKey = resolveWalletKey(options);
          return Keypair.fromWalletKey(walletKey);
        }
        if (options.signature) {
          return Keypair.fromSignature(options.signature);
        }
        return new Keypair();
      }

      const derivation: 'wallet-signature' | 'provided-signature' | 'random' =
        options.signMessage ? 'wallet-signature'
        : options.signature ? 'provided-signature'
        : 'random';

      const derivationLabel = options.signMessage
        ? 'Derived Veil keypair from wallet signature'
        : options.signature
          ? 'Derived Veil keypair from provided signature'
          : 'Generated new Veil keypair';

      // JSON mode: no prompts, no save, just output JSON
      if (options.json) {
        const kp = await createKp();
        console.log(JSON.stringify({
          veilKey: kp.privkey,
          veilPrivateKey: kp.privkey,
          depositKey: kp.depositKey(),
          derivation,
        }, null, 2));
        process.exit(0);
        return;
      }

      // No-save mode: print but don't save
      if (!options.save) {
        const kp = await createKp();
        console.log(`\n${derivationLabel}:\n`);
        console.log('Veil Private Key:');
        console.log(`  ${kp.privkey}\n`);
        console.log('Deposit Key (register this on-chain):');
        console.log(`  ${kp.depositKey()}\n`);
        console.log('(Not saved - run without --no-save to save to .env.veil)');
        process.exit(0);
        return;
      }

      // Check if VEIL_KEY already exists (unless --force)
      const keyExists = veilKeyExistsAt(envPath);
      
      if (keyExists && !options.force) {
        console.log(`\nWARNING: A Veil key already exists in ${envPath}`);
        const proceed = await confirm('Create a new key? This will overwrite the existing one');
        if (!proceed) {
          console.log('Aborted. Existing key preserved.');
          process.exit(0);
          return;
        }
      }
      
      const kp = await createKp();
      
      console.log(`\n${derivationLabel}:\n`);
      console.log('Veil Private Key:');
      console.log(`  ${kp.privkey}\n`);
      console.log('Deposit Key (register this on-chain):');
      console.log(`  ${kp.depositKey()}\n`);
      
      saveVeilKeypair(kp.privkey!, kp.depositKey(), envPath);
      console.log(`Saved to ${envPath}`);
      console.log('\nNext step: veil register');
      process.exit(0);
    });

  return init;
}
