/**
 * Type definitions for Veil SDK
 */

/**
 * Supported tokens
 */
export type Token = 'ETH' | 'USDC' | 'BTC';

/**
 * Encrypted message format (x25519-xsalsa20-poly1305)
 */
export interface EncryptedMessage {
  version: string;
  nonce: string;
  ephemPublicKey: string;
  ciphertext: string;
}

/**
 * Contract addresses for a network
 */
export interface NetworkAddresses {
  entry: `0x${string}`;
  ethPool: `0x${string}`;
  ethQueue: `0x${string}`;
  usdcPool: `0x${string}`;
  usdcQueue: `0x${string}`;
  usdcToken: `0x${string}`;
  btcPool: `0x${string}`;
  btcQueue: `0x${string}`;
  btcToken: `0x${string}`;
  chainId: number;
  relayUrl: string;
}

/**
 * Options for building a register transaction
 */
export interface RegisterTxOptions {
  depositKey: string;
}

/**
 * Options for building a deposit transaction
 */
export interface DepositTxOptions {
  depositKey: string;
  fallbackReceiver: `0x${string}`;
  amount: string;
  token?: Token;
}

/**
 * Transaction data returned by build functions
 */
export interface TransactionData {
  to: `0x${string}`;
  data: `0x${string}`;
  value?: bigint;
}

/**
 * Pool configuration
 */
export interface PoolConfig {
  decimals: number;
  displayDecimals: number;
  symbol: string;
  name: string;
}

/**
 * Pending deposit from queue contract
 */
export interface PendingDeposit {
  nonce: string;
  status: 'pending' | 'accepted' | 'rejected' | 'refunded';
  amount: string;
  amountWei: string;
  timestamp: string;
}

/**
 * Result from getQueueBalance
 */
export interface QueueBalanceResult {
  address: string;
  queueBalance: string;
  queueBalanceWei: string;
  pendingDeposits: PendingDeposit[];
  pendingCount: number;
}

/**
 * UTXO info for private balance
 */
export interface UtxoInfo {
  index: number;
  amount: string;
  amountWei: string;
  isSpent: boolean;
}

/**
 * Result from getPrivateBalance
 */
export interface PrivateBalanceResult {
  privateBalance: string;
  privateBalanceWei: string;
  utxoCount: number;
  spentCount: number;
  unspentCount: number;
  utxos: UtxoInfo[];
}

// =============================================================================
// Relay Types
// =============================================================================

/**
 * Pool type for relay operations
 */
export type RelayPool = 'eth' | 'usdc' | 'btc';

/**
 * Type of relay transaction
 */
export type RelayType = 'withdraw' | 'transfer';

/**
 * Proof arguments for relay transaction
 */
export interface RelayProofArgs {
  proof: string;
  root: string;
  inputNullifiers: string[];
  outputCommitments: [string, string];
  publicAmount: string;
  extDataHash: string;
}

/**
 * External data for relay transaction
 */
export interface RelayExtData {
  recipient: string;
  extAmount: string;
  relayer: string;
  fee: string;
  encryptedOutput1: string;
  encryptedOutput2: string;
}

/**
 * Metadata for relay transaction (optional)
 */
export interface RelayMetadata {
  amount?: string;
  recipient?: string;
  inputUtxoCount?: number;
  outputUtxoCount?: number;
}

/**
 * Request body for relay service
 */
export interface RelayRequest {
  type: RelayType;
  proofArgs: RelayProofArgs;
  extData: RelayExtData;
  metadata?: RelayMetadata;
}

/**
 * Response from relay service
 */
export interface RelayResponse {
  success: boolean;
  transactionHash: string;
  blockNumber: string;
  gasUsed: string;
  status: string;
  network: string;
}

/**
 * Error response from relay service
 */
export interface RelayErrorResponse {
  error: string;
  message?: string;
  retryAfter?: number;
  network?: string;
}

/**
 * Options for submitRelay function
 */
export interface SubmitRelayOptions {
  /** Type of transaction: 'withdraw' or 'transfer' */
  type: RelayType;
  /** Pool to use: 'eth' or 'usdc' */
  pool?: RelayPool;
  /** Proof arguments generated by ZK prover */
  proofArgs: RelayProofArgs;
  /** External data for the transaction */
  extData: RelayExtData;
  /** Optional metadata */
  metadata?: RelayMetadata;
  /** Custom relay URL (overrides default) */
  relayUrl?: string;
}

// =============================================================================
// Withdraw/Transfer Types
// =============================================================================

/**
 * Options for building a withdrawal proof
 */
export interface BuildWithdrawProofOptions {
  /** Amount to withdraw (human readable, e.g., "0.1") */
  amount: string;
  /** Recipient address for withdrawal */
  recipient: `0x${string}`;
  /** User's keypair for signing */
  keypair: import('./keypair.js').Keypair;
  /** Pool to withdraw from (default: 'eth') */
  pool?: RelayPool;
  /** Optional RPC URL */
  rpcUrl?: string;
  /** Progress callback */
  onProgress?: (stage: string, detail?: string) => void;
}

/**
 * Options for building a transfer proof
 */
export interface BuildTransferProofOptions {
  /** Amount to transfer (human readable, e.g., "0.1") */
  amount: string;
  /** Recipient's address (must be registered) */
  recipientAddress: `0x${string}`;
  /** Sender's keypair */
  senderKeypair: import('./keypair.js').Keypair;
  /** Pool to transfer in (default: 'eth') */
  pool?: RelayPool;
  /** Optional RPC URL */
  rpcUrl?: string;
  /** Progress callback */
  onProgress?: (stage: string, detail?: string) => void;
}

/**
 * Result from building a withdrawal or transfer proof
 */
export interface ProofBuildResult {
  /** Proof arguments for on-chain verification */
  proofArgs: RelayProofArgs;
  /** External data for transaction */
  extData: RelayExtData;
  /** Number of input UTXOs used */
  inputCount: number;
  /** Number of output UTXOs created */
  outputCount: number;
  /** Amount being withdrawn/transferred */
  amount: string;
}

/**
 * Result from executing a withdrawal
 */
export interface WithdrawResult {
  /** Whether the withdrawal was successful */
  success: boolean;
  /** Transaction hash */
  transactionHash: string;
  /** Block number of the transaction */
  blockNumber: string;
  /** Amount withdrawn */
  amount: string;
  /** Recipient address */
  recipient: string;
}

/**
 * Result from executing a transfer
 */
export interface TransferResult {
  /** Whether the transfer was successful */
  success: boolean;
  /** Transaction hash */
  transactionHash: string;
  /** Block number of the transaction */
  blockNumber: string;
  /** Amount transferred */
  amount: string;
  /** Recipient address */
  recipient: string;
}

/**
 * UTXO selection result
 */
export interface UtxoSelectionResult {
  /** Selected UTXOs */
  selectedUtxos: import('./utxo.js').Utxo[];
  /** Total amount of selected UTXOs (wei) */
  totalSelected: bigint;
  /** Change amount to return to sender (wei) */
  changeAmount: bigint;
}
